spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-db:5432/bank_service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
    hibernate:
      ddl-auto: update