apiVersion: v1
kind: Service
metadata:
  name: giga-bank-service
  namespace: giga-bank
  labels:
    app: giga-bank
spec:
  selector:
    app: giga-bank
    component: main-application
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP